#
# PERMISSIONS : 
# - banitems.reload | permet à un joueur de recharger le fichier de configuration depuis le jeu
# - banitems.bypass | permet à un joueur de contourner la détection/suppression d'objets
#
# -------------------
#
# ---- banned_items EXEMPLE COMPLET ----
#
# banned_items:
#   - BEDROCK
#   - GÂTEAU
#   - SEAU_D_EAU

banned_items:
  - BEDROCK

# Message envoyé à un joueur lorsqu'un objet est retiré de son inventaire
# %item% représente le nom de l'objet
messages:
  removal: "§c%item% a été enlevé de ton inventaire"
